[project]
name = "rerun-c3d"
dynamic = ["version"]
dependencies = [
    "ezc3d",
    "numpy",
    "rerun-sdk",
    "trimesh",
    ]
authors = [{name = "Pierre Puchaud", email = "puchaud.pierre@gmail.com"}]
maintainers = [{name = "Pierre Puchaud", email = "puchaud.pierre@gmail.com"}]
description = "A Python package to rerun C3D files."
license = {file = "LICENSE"}
readme = "README.md"
keywords = ["c3d", "motion capture", "rerun", "biorbd", "pyomeca"]

[project.urls]
homepage = "http://github.com/Ipuch/pyorerun"

