name: Run the tests

on: [pull_request]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            label: linux-64
            prefix: /usr/share/miniconda3/envs/pyorerun
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          use-mamba: true
          activate-environment: pyorerun
          environment-file: environment.yml
        
      - name: Print mamba info
        run: | 
          conda info
          conda list

      - name: Install extra dependencies
        run: conda install pytest-cov black pytest pytest-cov codecov -cconda-forge

      - name: Install pyorerun with pip
        run: pip install .

      - name: Run the actual tests
        run: pytest -v --color=yes --cov-report term-missing --cov=pyorerun tests
        
      - name: Upload coverage to Codecov
        run: codecov
        if: matrix.label == 'linux-64'
